#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtwebkit
Version  : 5.5.1
Release  : 1
URL      : https://github.com/qt/qtwebkit/archive/v5.5.1.tar.gz
Source0  : https://github.com/qt/qtwebkit/archive/v5.5.1.tar.gz
Summary  : Web content engine for GTK+
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause GPL-2.0 GPL-3.0 ICU LGPL-2.0 LGPL-2.1 LGPL-3.0 MIT
Requires: qtwebkit-license
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-qmake
BuildRequires : libXcomposite-dev
BuildRequires : libXrender-dev
BuildRequires : libwebp-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Multimedia)
BuildRequires : pkgconfig(Qt5MultimediaWidgets)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5OpenGL)
BuildRequires : pkgconfig(Qt5PrintSupport)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5QuickTest)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5Xml)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pkgconfig(zlib)
BuildRequires : qtdeclarative-dev
BuildRequires : zlib-dev

%description
The purpose of this project is to concatenate all the BuildLog.htm
output files from each project into a single output file.

%package license
Summary: license components for the qtwebkit package.
Group: Default

%description license
license components for the qtwebkit package.


%prep
%setup -q -n qtwebkit-5.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
%qmake
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1535558507
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/qtwebkit
cp LICENSE.GPLv2 %{buildroot}/usr/share/doc/qtwebkit/LICENSE.GPLv2
cp LICENSE.GPLv3 %{buildroot}/usr/share/doc/qtwebkit/LICENSE.GPLv3
cp LICENSE.LGPLv21 %{buildroot}/usr/share/doc/qtwebkit/LICENSE.LGPLv21
cp LICENSE.LGPLv3 %{buildroot}/usr/share/doc/qtwebkit/LICENSE.LGPLv3
cp Source/JavaScriptCore/COPYING.LIB %{buildroot}/usr/share/doc/qtwebkit/Source_JavaScriptCore_COPYING.LIB
cp Source/JavaScriptCore/icu/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Source_JavaScriptCore_icu_LICENSE
cp Source/ThirdParty/ANGLE/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Source_ThirdParty_ANGLE_LICENSE
cp Source/ThirdParty/ANGLE/src/third_party/compiler/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Source_ThirdParty_ANGLE_src_third_party_compiler_LICENSE
cp Source/ThirdParty/gtest/COPYING %{buildroot}/usr/share/doc/qtwebkit/Source_ThirdParty_gtest_COPYING
cp Source/ThirdParty/leveldb/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Source_ThirdParty_leveldb_LICENSE
cp Source/WTF/icu/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Source_WTF_icu_LICENSE
cp Source/WTF/wtf/dtoa/COPYING %{buildroot}/usr/share/doc/qtwebkit/Source_WTF_wtf_dtoa_COPYING
cp Source/WTF/wtf/dtoa/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Source_WTF_wtf_dtoa_LICENSE
cp Source/WebCore/LICENSE-APPLE %{buildroot}/usr/share/doc/qtwebkit/Source_WebCore_LICENSE-APPLE
cp Source/WebCore/LICENSE-LGPL-2 %{buildroot}/usr/share/doc/qtwebkit/Source_WebCore_LICENSE-LGPL-2
cp Source/WebCore/LICENSE-LGPL-2.1 %{buildroot}/usr/share/doc/qtwebkit/Source_WebCore_LICENSE-LGPL-2.1
cp Source/WebCore/icu/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Source_WebCore_icu_LICENSE
cp Source/WebCore/inspector/front-end/ace/LICENSE.txt %{buildroot}/usr/share/doc/qtwebkit/Source_WebCore_inspector_front-end_ace_LICENSE.txt
cp Source/WebCore/inspector/front-end/cm/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Source_WebCore_inspector_front-end_cm_LICENSE
cp Source/WebInspectorUI/UserInterface/External/CodeMirror/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Source_WebInspectorUI_UserInterface_External_CodeMirror_LICENSE
cp Source/WebKit/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Source_WebKit_LICENSE
cp Tools/Scripts/webkitpy/thirdparty/mod_pywebsocket/COPYING %{buildroot}/usr/share/doc/qtwebkit/Tools_Scripts_webkitpy_thirdparty_mod_pywebsocket_COPYING
cp Tools/TestResultServer/static-dashboards/LICENSE.dygraph.txt %{buildroot}/usr/share/doc/qtwebkit/Tools_TestResultServer_static-dashboards_LICENSE.dygraph.txt
cp Tools/iExploder/iexploder-1.7.2/LICENSE.txt %{buildroot}/usr/share/doc/qtwebkit/Tools_iExploder_iexploder-1.7.2_LICENSE.txt
cp Tools/mangleme/LICENSE %{buildroot}/usr/share/doc/qtwebkit/Tools_mangleme_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/qtwebkit/LICENSE.GPLv2
/usr/share/doc/qtwebkit/LICENSE.GPLv3
/usr/share/doc/qtwebkit/LICENSE.LGPLv21
/usr/share/doc/qtwebkit/LICENSE.LGPLv3
/usr/share/doc/qtwebkit/Source_JavaScriptCore_COPYING.LIB
/usr/share/doc/qtwebkit/Source_JavaScriptCore_icu_LICENSE
/usr/share/doc/qtwebkit/Source_ThirdParty_ANGLE_LICENSE
/usr/share/doc/qtwebkit/Source_ThirdParty_ANGLE_src_third_party_compiler_LICENSE
/usr/share/doc/qtwebkit/Source_ThirdParty_gtest_COPYING
/usr/share/doc/qtwebkit/Source_ThirdParty_leveldb_LICENSE
/usr/share/doc/qtwebkit/Source_WTF_icu_LICENSE
/usr/share/doc/qtwebkit/Source_WTF_wtf_dtoa_COPYING
/usr/share/doc/qtwebkit/Source_WTF_wtf_dtoa_LICENSE
/usr/share/doc/qtwebkit/Source_WebCore_LICENSE-APPLE
/usr/share/doc/qtwebkit/Source_WebCore_LICENSE-LGPL-2
/usr/share/doc/qtwebkit/Source_WebCore_LICENSE-LGPL-2.1
/usr/share/doc/qtwebkit/Source_WebCore_icu_LICENSE
/usr/share/doc/qtwebkit/Source_WebCore_inspector_front-end_ace_LICENSE.txt
/usr/share/doc/qtwebkit/Source_WebCore_inspector_front-end_cm_LICENSE
/usr/share/doc/qtwebkit/Source_WebInspectorUI_UserInterface_External_CodeMirror_LICENSE
/usr/share/doc/qtwebkit/Source_WebKit_LICENSE
/usr/share/doc/qtwebkit/Tools_Scripts_webkitpy_thirdparty_mod_pywebsocket_COPYING
/usr/share/doc/qtwebkit/Tools_TestResultServer_static-dashboards_LICENSE.dygraph.txt
/usr/share/doc/qtwebkit/Tools_iExploder_iexploder-1.7.2_LICENSE.txt
/usr/share/doc/qtwebkit/Tools_mangleme_LICENSE
